Release 0.4.1. 	* Add retry feature to get interface address.
--HG--
branch : HEAD

diff --git a/src/add-to-env.in b/src/add-to-env.in
--- a/src/add-to-env.in
+++ b/src/add-to-env.in
@@ -14,28 +14,28 @@ EOF
 verbose=1
 
 while true ; do
-    case "$1" in
-    -h|--help)
-	usage
-	exit 0
-	;;
-    -v|--verbose)
-	verbose=1
-	shift
-	;;
-    -q|--quiet)
-	verbose=0
-	shift
-	;;
-    --)
-	shift
-	break
-	;;
-    *)
-	echo "getopt(1) internal error!!"
-	exit 1
-	;;
-    esac
+	case "$1" in
+		-h|--help)
+			usage
+			exit 0
+			;;
+		-v|--verbose)
+			verbose=1
+			shift
+			;;
+		-q|--quiet)
+			verbose=0
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "getopt(1) internal error!!"
+			exit 1
+			;;
+	esac
 done
 
 ln_vopt=''
@@ -43,10 +43,10 @@ cp_vopt=''
 rm_vopt=''
 mkdir_vopt=''
 if [ "x$verbose" = "x1" ]; then
-    ln_vopt=-v
-    cp_vopt=-v
-    rm_vopt=-v
-    mkdir_vopt=-v
+	ln_vopt=-v
+	cp_vopt=-v
+	rm_vopt=-v
+	mkdir_vopt=-v
 fi
 
 LN="ln $ln_vopt"
@@ -55,15 +55,15 @@ RM="rm $rm_vopt"
 MKDIR="mkdir $mkdir_vopt"
 
 function vecho () {
-    if [ "x$verbose" = "x1" ]; then
-	echo "$@"
-    fi
+	if [ "x$verbose" = "x1" ]; then
+		echo "$@"
+	fi
 }
 
 function vrun () {
-    if [ "x$verbose" = "x1" ]; then
-	"$@"
-    fi
+	if [ "x$verbose" = "x1" ]; then
+		"$@"
+	fi
 }
 
 cachedir=@sysconfdir@/network-env/cache
@@ -77,27 +77,27 @@ function do_cache () {
 }
 
 if [ "x$1" = "x" ]; then
-    usage
-    exit
+	usage
+	exit
 fi
 
 file="$1"
 
 if [ x`expr match "$file" "/"` = "x0" ]; then
-    echo "FILE_TO_ADD must be absolute path"
-    exit 1
+	echo "FILE_TO_ADD must be absolute path"
+	exit 1
 fi
 
 if [ -e ${cachedir}${file} ]; then
-    ${file} already have been added.
-    exit 1
+	${file} already have been added.
+	exit 1
 fi
 
 do_cache ${file}
 
 for env in `list-env`
 do
-    dest=@sysconfdir@/network-env/envs/${env}${file}
-    $MKDIR -p `dirname ${dest}`
-    $CP -p ${file} ${dest}
+	dest=@sysconfdir@/network-env/envs/${env}${file}
+	$MKDIR -p `dirname ${dest}`
+	$CP -p ${file} ${dest}
 done
diff --git a/src/nenv-addfile.in b/src/nenv-addfile.in
--- a/src/nenv-addfile.in
+++ b/src/nenv-addfile.in
@@ -17,65 +17,65 @@ verbose=1
 no_act=0
 
 while true ; do
-    case "$1" in
-    -h|--help)
-	usage
-	exit 0
-	;;
-    -n|--no-act)
-	no_act=1
-	shift
-	;;
-    -v|--verbose)
-	verbose=1
-	shift
-	;;
-    -q|--quiet)
-	verbose=0
-	shift
-	;;
-    --)
-	shift
-	break
-	;;
-    *)
-	echo "$program getopt(1) internal error!!($1)"
-	exit 1
-	;;
-    esac
+	case "$1" in
+		-h|--help)
+			usage
+			exit 0
+			;;
+		-n|--no-act)
+			no_act=1
+			shift
+			;;
+		-v|--verbose)
+			verbose=1
+			shift
+			;;
+		-q|--quiet)
+			verbose=0
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "$program getopt(1) internal error!!($1)"
+			exit 1
+			;;
+	esac
 done
 
 file="$1"
 if [ "x$file" = "x" ]; then
-    usage
-    exit
+	usage
+	exit
 fi
 
 common_funcs=@libdir@/network-env/common-funcs
 
 if [ ! -x $common_funcs ]; then
-    echo "Installation doesn't finish correctly!"
-    echo "$common_funcs is not found!"
+	echo "Installation doesn't finish correctly!"
+	echo "$common_funcs is not found!"
 fi
 
 . ${common_funcs}
 def_command $verbose $no_act
 
 if [ x`expr match "$file" "/"` = "x0" ]; then
-    echo "FILE_TO_ADD must be absolute path."
-    exit 1
+	echo "FILE_TO_ADD must be absolute path."
+	exit 1
 fi
 
 if [ -e ${cachedir}${file} ]; then
-    echo "${file} already have been added."
-    exit 1
+	echo "${file} already have been added."
+	exit 1
 fi
 
 do_cache ${file}
 
 for env in `nenv-list`
 do
-    dest=@sysconfdir@/network-env/envs/${env}${file}
-    $MKDIR -p `dirname ${dest}`
-    $CP -p ${file} ${dest}
+	dest=@sysconfdir@/network-env/envs/${env}${file}
+	$MKDIR -p `dirname ${dest}`
+	$CP -p ${file} ${dest}
 done
diff --git a/src/nenv-copyfile.in b/src/nenv-copyfile.in
--- a/src/nenv-copyfile.in
+++ b/src/nenv-copyfile.in
@@ -17,39 +17,39 @@ verbose=1
 no_act=0
 
 while true ; do
-    case "$1" in
-    -h|--help)
-	usage
-	exit 0
-	;;
-    -n|--no-act)
-	no_act=1
-	shift
-	;;
-    -v|--verbose)
-	verbose=1
-	shift
-	;;
-    -q|--quiet)
-	verbose=0
-	shift
-	;;
-    --)
-	shift
-	break
-	;;
-    *)
-	echo "$program getopt(1) internal error!!($1)"
-	exit 1
-	;;
-    esac
+	case "$1" in
+		-h|--help)
+			usage
+			exit 0
+			;;
+		-n|--no-act)
+			no_act=1
+			shift
+			;;
+		-v|--verbose)
+			verbose=1
+			shift
+			;;
+		-q|--quiet)
+			verbose=0
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "$program getopt(1) internal error!!($1)"
+			exit 1
+			;;
+	esac
 done
 
 common_funcs=@libdir@/network-env/common-funcs
 
 if [ ! -x $common_funcs ]; then
-    echo "Installation doesn't finish correctly!"
-    echo "$common_funcs is not found!"
+	echo "Installation doesn't finish correctly!"
+	echo "$common_funcs is not found!"
 fi
 
 . ${common_funcs}
@@ -59,30 +59,30 @@ file="$1"
 src=$2
 dest=$3
 if [ "x$file" = "x" -o "x$src" = "x" -o "x$dest" = "x" ]; then
-    usage
-    exit
+	usage
+	exit
 fi
 srcconf=`nenv_confdir $src`
 destconf=`nenv_confdir $dest`
 
 if [ ! -d $srcconf ]; then
-    echo "No such environment: $src"
-    exit 1
+	echo "No such environment: $src"
+	exit 1
 fi
 
 if [ ! -d $destconf ]; then
-    echo "No such environment: $dest"
-    exit 1
+	echo "No such environment: $dest"
+	exit 1
 fi
 
 if [ x`expr match "$file" "/"` = "x0" ]; then
-    echo "FILE_TO_ADD must be absolute path"
-    exit 1
+	echo "FILE_TO_ADD must be absolute path"
+	exit 1
 fi
 
 if [ ! -e $srcconf$file ]; then
-    echo "${file} does not exist in enviroment $src".
-    exit 1
+	echo "${file} does not exist in enviroment $src".
+	exit 1
 fi
 
 $MKDIR -p `dirname $destconf$file`
diff --git a/src/nenv-create.in b/src/nenv-create.in
--- a/src/nenv-create.in
+++ b/src/nenv-create.in
@@ -8,7 +8,7 @@ args=`getopt --name="$program" --options="hnvq" --longoptions="help,no-act,verbo
 eval set -- "$args"
 
 function usage() {
-    cat <<"EOF"
+	cat <<"EOF"
 Usage: $program [-hnq] ENV_LOGICAL_NAME
 EOF
 }
@@ -17,33 +17,33 @@ verbose=1
 no_act=0
 
 while true ; do
-    case "$1" in
-    -h|--help)
-	usage
-	exit 0
-	;;
-    -v|--verbose)
-	verbose=1
-	shift
-	;;
-    -q|--quiet)
-	verbose=0
-	shift
-	;;
-    --)
-	shift
-	break
-	;;
-    *)
-	echo "$program getopt(1) internal error!!($1)"
-	exit 1
-	;;
-    esac
+	case "$1" in
+		-h|--help)
+			usage
+			exit 0
+			;;
+		-v|--verbose)
+			verbose=1
+			shift
+			;;
+		-q|--quiet)
+			verbose=0
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "$program getopt(1) internal error!!($1)"
+			exit 1
+			;;
+	esac
 done
 
 if [ "x$1" = "x" ]; then
-    usage
-    exit
+	usage
+	exit
 fi
 
 envname="$1"
@@ -51,8 +51,8 @@ envname="$1"
 common_funcs=@libdir@/network-env/common-funcs
 
 if [ ! -x $common_funcs ]; then
-    echo "Installation doesn't finish correctly!"
-    echo "$common_funcs is not found!"
+	echo "Installation doesn't finish correctly!"
+	echo "$common_funcs is not found!"
 fi
 
 . ${common_funcs}
@@ -60,23 +60,23 @@ envdir=`nenv_confdir $envname`
 
 
 if [ ! -d ${cachedir} ]; then
-    $RM -f ${cachedir}
-    $MKDIR -p ${cachedir}
-    true
+	$RM -f ${cachedir}
+	$MKDIR -p ${cachedir}
+	true
 fi
 
 if [ -d ${envdir} ]; then
-    if [ "${envname}" != "stand-alone" ]; then
-	echo "warning: Environment ${envname} is already exist."
-    fi
-    exit 0
+	if [ "${envname}" != "stand-alone" ]; then
+		echo "warning: Environment ${envname} is already exist."
+	fi
+	exit 0
 fi
 
 #$MKDIR -p ${envdir}
 
 default_env_dir=@sysconfdir@/network-env/envs/stand-alone
 if [ $default_env_dir != $envdir ]; then
-    if [ -d $default_env_dir ]; then
-	$CP -a ${default_env_dir} ${envdir}
-    fi
+	if [ -d $default_env_dir ]; then
+		$CP -a ${default_env_dir} ${envdir}
+	fi
 fi
diff --git a/src/nenv-list.in b/src/nenv-list.in
--- a/src/nenv-list.in
+++ b/src/nenv-list.in
@@ -7,15 +7,15 @@ envname=$1
 envs_dir=@sysconfdir@/network-env/envs
 
 if [ -z "$envname" ]; then
-    ls $envs_dir
-    exit 0
+	ls $envs_dir
+	exit 0
 fi
 
 common_funcs=@libdir@/network-env/common-funcs
 
 if [ ! -x $common_funcs ]; then
-    echo "Installation doesn't finish correctly!"
-    echo "$common_funcs is not found!"
+	echo "Installation doesn't finish correctly!"
+	echo "$common_funcs is not found!"
 fi
 
 . ${common_funcs}
@@ -23,8 +23,8 @@ def_command $verbose $no_act
 envdir=`nenv_confdir $envname`
 
 if [ ! -d ${envdir} ]; then
-    echo "Environment $envname does not exist."
-    exit 1
+	echo "Environment $envname does not exist."
+	exit 1
 fi
 
 cd $envdir
